# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('description', models.TextField()),
                ('price_CAD', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='password',
            field=models.CharField(max_length=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='logininfo',
            name='username',
            field=models.CharField(max_length=10, verbose_name=''),
        ),
    ]
