# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_profilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
