# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170510_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='RevenueInfo',
        ),
    ]
