# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0006_auto_20170510_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenueinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='revenueinfo',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
