# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True),
        ),
    ]
