# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_revenueinfo_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenueinfo',
            name='user',
        ),
    ]
