# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-16 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20170514_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revenueinfo',
            old_name='amount_spent',
            new_name='total_amount_spent',
        ),
        migrations.RemoveField(
            model_name='revenueinfo',
            name='total',
        ),
    ]
