# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20170528_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='date_bought',
            field=models.DateField(null=True),
        ),
    ]
