# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-12 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20170528_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedprofile',
            name='img',
            field=models.ImageField(default='img_folder/None/no-img.jpg', upload_to='img_folder'),
        ),
    ]
