# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-12 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_extendedprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedprofile',
            name='img',
            field=models.ImageField(default='tracker/img/no-img.jpg', upload_to='tracker/img/'),
        ),
    ]
