# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20170611_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedprofile',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
